### ISSUE TITLE
Some media images show 404 for some people

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#100]
### Steps to reproduce

In #loadtesting:ubuntu.com recently shared an image. Some people apparently see it since they reacted to it, but not everyone. 

### Outcome

For me it spins, and looking at devtools it tries to hit https://chat-server.ubuntu.com/_matrix/media/v3/download/ubuntu.com/oSPrBcOXSqkDcMRqbFdWDZxv which gives a 404.

### Client information

**Name**: Element Web (in an Electron Container)

**Comment by amandahla** [comment]
Closing this issue since no longer applies, thanks for the input!
