### ISSUE TITLE
Element client shows "Unable to decrypt: The sender's device has not sent us the keys for this message."

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#101]
### Steps to reproduce

1. Where are you starting? What can you see?
While you join an encrypted room and try to read messages, this warning appears.

3. What do you click?
Read encrypted message.

5. More steps…

#### What did you expect?
Read encrypted messages.

#### What happened instead?
A warning is shown.

![image](https://github.com/canonical/synapse-operator/assets/12564014/92f0965a-ed08-4be5-8b38-cd331f70e26b)

### Client information

**Name**: Mobile client
**Version**:
**OS and install type**: Iphone

**Comment by amandahla** [comment]
Related:
https://github.com/vector-im/element-web/issues/19748

**Comment by ripper81** [comment]
Hi, i am also affected by this. In my case the problem occurs on Android. The desktop APP is working flawless.

**Comment by amandahla** [comment]
This issue is now outdated and no longer applies. Closing it for now.
