### ISSUE TITLE
Please enable federation with gnome.org

### ISSUE THREAD

**Issue by jbicha** [canonical/synapse-operator#115]
#### What would you like to do?

I want to use my ubuntu.com Matrix account to access gnome.org Matrix channels.

#### Why would you like to do it?

I need to connect to GNOME Matrix to do my job as a member of the GNOME Release Team and coordinate my GNOME development and packaging work. I need to use my ubuntu.com account for Canonical and Ubuntu work. I do not want to be required to use 2 different Matrix accounts. I also like advertising that my GNOME work is done as a member of the Ubuntu community (similar to how I use my ubuntu.com or canonical.com email addresses).

#### How would you like to achieve it?

It ought to be as simple from the user side as configuring `gnome.org` as an additional Matrix server.

### Additional context

Also, we should allow people with gnome.org accounts to easily connect to the ubuntu.com Matrix. Let me know if you would prefer a separate issue be filed for that.

https://wiki.gnome.org/GettingInTouch/Matrix

If you need to contact GNOME admins, I think ideally you would use https://matrix.to/#/#infrastructure:gnome.org or perhaps https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues

**Comment by merkata** [comment]
Sounds fair :) Thanks for raising this @jbicha , taking a look.

**Comment by jbicha** [comment]
@merkata Is this issue being worked on?

**Comment by merkata** [comment]
@jbicha sorry for the lack of update, this is being worked on together with #134 by @gregory-schiano , the solution aims to resolve the issue altogether and have federation enabled by default instead of allowing specific servers to be federated.

**Comment by jbicha** [comment]
@merkata I am able to connect to gnome.org now, so I'll close this issue.
