### ISSUE TITLE
Refactor removing config generation from the pebble service

### ISSUE THREAD

**Issue by jdkandersson** [canonical/synapse-operator#123]
Please refactor these lines moving the config generation to the event handler which can then use pebble service to restart.

https://github.com/canonical/synapse-operator/blob/eb44f4959a00040f08b98470f8b17cae4cc616da/src/pebble.py#L86C1-L106C57

**Comment by cbartz** [comment]
@amandahla It seems this has been done, can you confirm and close the issue, please?

**Comment by amandahla** [comment]
Confirmed, thanks.
