### ISSUE TITLE
Please enable federation for four additional servers

### ISSUE THREAD

**Issue by ArrayBolt3** [canonical/synapse-operator#134]
#### What would you like to do?
Enable federation between the ubuntu.com Matrix server and the following four servers:
* im.kde.org
* linuxdelta.com
* fedoraproject.org
* gnulinux.club

#### Why would you like to do it?
* im.kde.org: necessary to interact with the appservice IRC bridge bot for KDE-related rooms.
* linuxdelta.com: needed by Simon Quigley, I believe this is a server run by his employer (@tsimonq2 please correct me if I'm wrong)
* fedoraproject.org: server used by Fedora, I contribute to Fedora sporadically and would like to interact with their rooms
* gnulinux.club: this homeserver is run by a sysadmin friend of mine, I help him moderate some rooms there and also enjoy talking with him and others there.

#### How would you like to achieve it?
However federation is usually enabled.

### Have you considered any alternatives?

I could keep using my Matrix.org account but having two Element instances open is tricky. This alternative is also unsatisfactory for the im.kde.org server, and may be unsatisfactory for linuxdelta.com.

### Additional context

No additional context.

**Comment by tsimonq2** [comment]
LinuxDelta.com is a server ran by Altispeed Technologies. Myself or Noah Chelliah would be the contacts for this.

**Comment by Conan-Kudo** [comment]
> fedoraproject.org

Fedora has a dual-server setup, both `fedoraproject.org` and `fedora.im` need to be allowed through.

**Comment by Conan-Kudo** [comment]
There is also an openSUSE server on `opensuse.org`.

**Comment by tsimonq2** [comment]
matrix.lubuntu.me / lubuntu.me as well

**Comment by merkata** [comment]
Just a note that we are working on resolving this with a more permanent solution starting next week that will resolve this issue (cc @gregory-schiano)

**Comment by gregory-schiano** [comment]
Federation has been enabled globally, I'm closing this issue
