### ISSUE TITLE
Enhancement: Replace Mjolnir with Draupnir

### ISSUE THREAD

**Issue by TheArcaneBrony** [canonical/synapse-operator#152]
#### What would you like to do?
Replace Mjolnir deployment with [Draupnir](https://github.com/the-draupnir-project/Draupnir/)

#### Why would you like to do it?
Draupnir is a continuation of Mjolnir (by a former developer), which fixes multiple issues, such as:
- Room alias resolution failure causing removal of all server ACLs
   - https://github.com/matrix-org/mjolnir/issues/435
   - https://github.com/matrix-org/mjolnir/issues/404
- Removing/explicitly overriding a ban may cause all (including the local) homeservers to get banned
    - https://github.com/matrix-org/mjolnir/issues/482

Draupnir also adds some nice usability improvements, such as prompting in the control room whether to write bans from individual rooms to policy lists, and simplifying the ban command by adding a flow that asks which list to write a ban to, and for what reason, rather than having to type this out manually.

#### How would you like to achieve it?
Replace Mjolnir with Draupnir

### Have you considered any alternatives?

Ensuring that any room is referenced to by internal room ID, and not by a mention, room alias, matrix.to or matrix:// URI, including replacing them in existing account data on the bot's user account.

### Additional context

Draupnir is a continuation (hard fork) of Mjolnir, by one of it's former maintainers.
As such, it is a drop-in replacement, and requires no configuration changes.

I am an external user, and focus on moderation within the realm of Matrix at large. You can reach me at @emma:conduit.rory.gay if more context and/or information is required.

**Comment by amandahla** [comment]
Relates https://github.com/canonical/synapse-operator/issues/96

**Comment by cbartz** [comment]
@amandahla Can you follow-up here, please (and create a ticket in the backlog if necessary)?

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
