### ISSUE TITLE
[Deployment] Disable ratelimits for @moderator:ubuntu.com

### ISSUE THREAD

**Issue by TheArcaneBrony** [canonical/synapse-operator#241]
### Enhancement Proposal

Draupnir/Mjolnir benefit from having ratelimits disabled. This is especially relevant with the `!<prefix> redact` command, which is *expected* to hit ratelimits on sending events (100 messages redacted = 100 new timeline events).
It's probably a good idea to disable ratelimits, in order to ensure the ability to take quick action (eg. high-volume spammers).

**Comment by merlijn-sebrechts** [comment]
We just had a spammer in the Ubuntu discussion room and redacting their messages happened really slowly: multiple minutes for 30-something messages. This is probably slow die to rate limit. Higher rate limit would help us combat spam quicker.

**Comment by kewisch** [comment]
FWIW rate limiting can be disabled per-user with the admin API at https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#override-ratelimiting-for-users

I had thought we've already taken this step, but let's double check.

**Comment by cbartz** [comment]
@gregory-schiano Can you have a look, please?

**Comment by gregory-schiano** [comment]
The rate limit for the admin user has been set to unlimited already first manually using the API, but also in the code when the moderator user is managed:
https://github.com/canonical/synapse-operator/blob/main/src/mjolnir.py#L222
