### ISSUE TITLE
Synapse charm review PR: Fix files in the charm project

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#49]
This issue should address comments regarding files in the charm project such as:
- actions.yaml
- charmcraft.yaml
- config.yaml
- icon.svg
- manifest.yaml
- metadata.yaml
- requirements.txt

Or anything not related to the code itself.
Reference: [List of files in the charm project](https://juju.is/docs/sdk/list-of-files-in-the-charm-project)

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332553975_

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332554524

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332555672

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332557396

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332562287

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332562835

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333914403

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336690815

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336696781

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336719231

**Comment by amandahla** [comment]
Ops, closed/reopened again :|

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342361501

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342501417

**Comment by cbartz** [comment]
Hi @amandahla , can this issue be closed?

**Comment by amandahla** [comment]
Yes, closing now :)
