### ISSUE TITLE
Synapse charm review PR: Fix documentation

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#50]
This issue should address comments regarding documentation only.

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332673366

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342325120

**Comment by cbartz** [comment]
@amandahla What is the status here, please?

**Comment by amandahla** [comment]
The charm has changed a lot since this was opened. Closing as it’s no longer relevant.
