### ISSUE TITLE
Synapse charm review PR: Fix rocks

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#51]
This issue should address comments regarding ROCKs only.

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336715781

**Comment by cbartz** [comment]
@amandahla What is the status here, please?

**Comment by amandahla** [comment]
The charm has changed a lot since this was opened. Closing as it’s no longer relevant.
