### ISSUE TITLE
Synapse charm review PR: Fix Python code

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#52]
This issue should address comments regarding Python code like:
- Variables names/location
- Libraries to be used
- Rephrase comments
- Docstrings
- Lint issues

Architectural changes (Observer/Service/Modules) should be addressed in a different issue.

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332739090

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332740425

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1332744132

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333901354

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333902754

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333921445

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333923971

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333938938

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333941169

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333947790

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333950217

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336716928

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336724493

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336725755

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336729338

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336742145

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336746810

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336797451

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338057843

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338059257

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338059906

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338061823

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338068936

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338074181

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338074742

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338076131

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1338076131

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342393258

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342423222

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342456050

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342463174

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342471314

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1342509218

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/77#discussion_r1371175901

**Comment by cbartz** [comment]
@amandahla What is the status here, please?

**Comment by amandahla** [comment]
The charm has changed a lot since this was opened. Closing as it’s no longer relevant.
