### ISSUE TITLE
Synapse charm review PR: Fix charm architecture

### ISSUE THREAD

**Issue by amandahla** [canonical/synapse-operator#54]
This issue should address comments regarding charm architecture like:
- Charm state changes
- Observers
- Services

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333930853

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1333963806

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336739911

**Comment by amandahla** [comment]
https://github.com/canonical/synapse-operator/pull/43#discussion_r1336756824

**Comment by cbartz** [comment]
@amandahla What is the status here, please?

**Comment by amandahla** [comment]
The charm has changed a lot since this was opened. Closing as it’s no longer relevant.
