### ISSUE TITLE
Metrics Dashboard

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#60]
### Enhancement Proposal

It would be great to have access to a metrics dashboard that will give us some stats on the matrix instance. This might be a requirement for load testing as well.

https://matrix-org.github.io/synapse/latest/metrics-howto.html

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
