### ISSUE TITLE
Disable Password Login

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#62]
### Enhancement Proposal

We use SSO exclusively. The password login should be disabled in [password_config](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#password_config). This will also avoid the profile settings where it looks like users can change their passwords.

**Comment by kewisch** [comment]
@amandahla while #77 is merged, it appears we haven't actually disabled this for the ubuntu server. can you take a look? QA STR:

1. Open private window, go to app.element.io
2. Edit homeserver to be ubuntu.com

Expected:
<img width="696" alt="image" src="https://github.com/canonical/synapse-operator/assets/607198/5c84edc7-fad8-4d86-ae57-6e4db211ad3d">

Actual right now:
<img width="679" alt="image" src="https://github.com/canonical/synapse-operator/assets/607198/ea808b38-54d1-4894-903c-ce06ff4717e5">

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
