### ISSUE TITLE
Tell people the server is temporary during testing

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#68]
### Enhancement Proposal

We need some way to tell people joining that the server state is temporary and we're in testing. Potentially leverage https://github.com/matrix-org/synapse/blob/develop/docs/consent_tracking.md

**Comment by kewisch** [comment]
It appears there is no way to do this other than setting a topic or having a bot greet people.

**Comment by amandahla** [comment]
Closing this issue since no longer apply, thanks for the input!
