### ISSUE TITLE
Allow guest access

### ISSUE THREAD

**Issue by Saviq** [canonical/synapse-operator#76]
### Enhancement Proposal

One of the important bits of IRC for me is the ability to join a conversation as a guest, no authentication required.

I'd hate for us to lose this, and that's a reason why all our websites still point at Libera web IRC, with the topic pointing at the Matrix room as the better way to consume it.

Ref. https://github.com/vector-im/element-web/issues/9264

We probably need per-room opt-{in,out} settings for this, too.

**Comment by kewisch** [comment]
Matrix has a setting to make room content viewable by anyone, and Element Web at least on app.element.io also has a guest mode. Both of these are helpful in this case.

**Comment by Saviq** [comment]
FWIW I don't think read-only is sufficient, this is about drive-by help for ppl that clicked a link to find help.

**Comment by kewisch** [comment]
Yeah. I can't trigger it now, but recently I somehow went to app.element.io and was immediately in a channel called Guest123123123. Needs investigation if we can do that on our element web.

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
