### ISSUE TITLE
Moderation: Rename mjolnir bot to "moderator" and make it a homeserver admin

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#81]
### Enhancement Proposal

moderator is more approachable in naming.

Also make sure mjolnir is a homeserver admin so it can make itself admin on channels.

**Comment by amandahla** [comment]
@kewisch Please could you give more details about it? The mjolnir user is already an admin.

**Comment by kewisch** [comment]
The mxid for Mozilla's mjolnir is `@moderator:mozilla.org` and the display name is `moderator`. Our bot is `@mjolnir:ubuntu.com` and is named mjolnir. 

Running `!mjolnir make admin` causes the message `Either the command is disabled or I am not running as homeserver administrator.` from mjolnir. I'll invite you to the test room.

**Comment by amandahla** [comment]
This issue was fixed but it seems that the problem is that Mjolnir configuration miss a "enableMakeRoomAdminCommand" item to be set to True. I only found out reference for this by checking the code 
https://github.com/matrix-org/mjolnir/blob/main/src/commands/MakeRoomAdminCommand.ts#L23

**Comment by amandahla** [comment]
I'm closing this issue since no longer applies, thanks for the input!
