### ISSUE TITLE
Element Web: Enable Markdown in room topics labs feature

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#86]
#### What would you like to do?
* Have Markdown in room topics rendered correctly

#### Why would you like to do it?
* Better transitioning from Mattermost and other similar platforms

#### How would you like to achieve it?
* Enable the labs feature once we have element web deployed:
  * https://github.com/vector-im/element-web/blob/develop/docs/config.md#labs-flags on how to configure labs features
  * https://github.com/vector-im/element-web/blob/develop/docs/labs.md for which labs features are available
  * Enable `feature_html_topic`

### Additional context

If we enable this, it still doesn't fix it for other clients. If someone is using Element Desktop, the will just see Markdown until Element offers this as a beta labs feature. We should work with our contacts to see when this can happen.

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
