### ISSUE TITLE
Investigate account suspension/removal when Ubuntu Member status has been removed

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#92]
### Your use case

If a person loses their Ubuntu Member status for the one or other reason, we need to ensure that there is a graceful way to deal with the account:
* They should no longer have access to the account
* We need to figure out how to deal with the account itself. Is the account purged and removed from all channels? Is it suspended temporarily in caes folks get their member status back? How to avoid collecting ghost accounts that lurk in channels.
* Some people might want to "keep" their account, but I don't think this is possible if they want to keep the mxid.

Mozilla has some issues here because the unique id that is tied to encryption is also tied to a single account, so they can't
1) recreate accounts that have been deleted
2) Let a staff member migrate to a community account.

### Additional context

Might be worth checking how we key the account, e.g. by openid, by email, etc.

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
