### ISSUE TITLE
Enable mjolnir as a synapse module

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#96]
### Your use case

Let's investigate enabling mjolnir as a synapse module. We do want to be able to moderate people regardless of the channel they are on, without explicitly inviting the moderator user. I don't see any immediate downsides, but I'm also not sure how it works.

https://github.com/matrix-org/mjolnir/blob/main/docs/synapse_module.md

**Comment by amandahla** [comment]
Note: test if it works together with Mjolnir bot.

**Comment by TheArcaneBrony** [comment]
To my awareness, the Synapse module *does not* work this way, it's purpose is to block invites (and blank messages), and by itself cannot ban members from rooms the moderator user is not an administrator in.

**Comment by cbartz** [comment]
@amandahla Can you follow-up here, please (and create a ticket in the backlog if necessary)?

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
