### ISSUE TITLE
Auto-join rooms when registering

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#98]
### Your use case

There is an `auto_join_rooms` config option. It would be great to give users the opportunity to join a room so they have something to get started in. @ilvipero to determine what a good initial set is. Potentially the space, otherwise an intro room like synchronicity, or a new room.

**Comment by amandahla** [comment]
This issue has been transferred to a Jira story for further tracking as a feature request. Closing this issue for now. Thanks for your input!
